import { primPut, primPutln, primClear, primWait, primWaitUntil, primIf, primElseif, primElse, primEndif, primSwitch, primCase, primDefault, primEndswitch, primMove, primEndRepeat, primRepeat, primWhile, primEndWhile, primStore, primFlushRam, primFunction, primEndFunction, primCall, primReturn, primTrackStart, primTrackStopAll, primTrackStop } from './prims.js';

export const primitiveSpecs = {
  'PRINT': primPut,
  'PRINTLN': primPutln,
  'CLEAR': primClear,
  'WAIT': primWait,
  'IF': primIf,
  'ELSEIF': primElseif,
  'ELSE': primElse,
  'ENDIF': primEndif,
  'SWITCH': primSwitch,
  'CASE': primCase,
  'DEFAULT': primDefault,
  'ENDSWITCH': primEndswitch,
  'MOVE': primMove,
  'REPEAT': primRepeat,
  'ENDREPEAT': primEndRepeat,
  'WHILE': primWhile,
  'WAITUNTIL': primWaitUntil,
  'ENDWHILE': primEndWhile,
  'STORE': primStore,
  'FLUSHRAM': primFlushRam,
  'FUNCTION': primFunction,
  'ENDFUNCTION': primEndFunction,
  'CALL': primCall,
  'RETURN': primReturn,
  'TRACKSTART': primTrackStart,
  'TRACKSTOPALL': primTrackStopAll,
  'TRACKSTOP': primTrackStop
};